defaults:
  sample_rate: 16000
  frame_length_ms: 30
  hop_length_ms: 15
  max_buffer_ms: 600
  channels: 1
  n_fft: 512

models:
  decision_tree:
    aggregate: true
    selector:
      enable: true

    features:
      mfcc:
        enable: true
        n_mfcc: 10
      mfcc_diff_norm:
        enable: true
        n_mfcc: 10
      short_time_energy:
        enable: true
      zero_crossing_rate:
        enable: true
      band_energy_ratio:
        enable: true
        lower_band:
          lower_bound: 0
          upper_bound: 70
        upper_band:
          lower_bound: 8000
          upper_bound: 16000
      autocorrelation_coefficient:
        enable: true
        min_lag_ms: 3
        max_lag_ms: 16
      spectral_rolloff_point:
        enable: true
        thr: 0.85
      spectrum_centroid:
        enable: true
      spectrum_spread:
        enable: true
      spectral_flux:
        enable: true

  gmm:
    aggregate: true
    selector:
      enable: true

    features:
      mfcc:
        enable: true
        n_mfcc: 10
      mfcc_diff_norm:
        enable: true
        n_mfcc: 10
      short_time_energy:
        enable: true
      zero_crossing_rate:
        enable: true
      band_energy_ratio:
        enable: true
        lower_band:
          lower_bound: 0
          upper_bound: 70
        upper_band:
          lower_bound: 8000
          upper_bound: 16000
      autocorrelation_coefficient:
        enable: true
        min_lag_ms: 3
        max_lag_ms: 16
      spectral_rolloff_point:
        enable: true
        thr: 0.85
      spectrum_centroid:
        enable: true
      spectrum_spread:
        enable: true
      spectral_flux:
        enable: true
