sample_rate = 16000
channels = 1
n_fft = 512

[buffers]
frame_length_ms = 20
hop_length_ms = 10
lt_len_ms = 300

[model]
name="decision_tree"

[features]
[features.band_energy_ratio]
low = 70
high = 4000

[features.autocorrelation_coefficient]
min_lag_ms = 3
max_lag_ms = 16

[features.spectral_rolloff_point]
threshold = 0.85
