[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "bp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.10.19"
dependencies = [
    "click>=8.3.1",
    "datasets[audio]>=4.5.0",
    "huggingface-hub>=1.4.1",
    "joblib==1.5.3",
    "librosa>=0.11.0",
    "numpy>=2.2.6",
    "safetensors>=0.4.0",
    "tomli>=2.4.0",
    "torch==2.9.1",
    "torchaudio>=2.0.0",
    "torchcodec==0.9.1",
    "wandb>=0.16.0",
]

[project.scripts]
smclassifier = "src.main:cli"

[tool.hatch.build.targets.wheel]
packages = ["src"]

[tool.uv.workspace]
members = [
    "dataset_scripts",
    "scripts",
]
