[project]
name = "dataset-scripts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.0"
dependencies = [
    "datasets[audio]>=4.5.0",
    "hf>=1.4.1",
    "jsonlines>=4.0.0",
    "pydub>=0.25.1",
    "silero-vad>=6.2.1",
    "soundfile>=0.13.1",
    "tqdm>=4.67.3",
]

[dependency-groups]
dev = [
    "ruff>=0.15.3",
    "ty>=0.0.19",
]
